### ISSUE TITLE
Not able to make my bot become online

### ISSUE THREAD

**Issue by Tahwi** [Devcord/cordlr-cli#172]
**Everytime** I try to make my bot go online (_node pathway_) it comes up with this:

> SyntaxError: Identifier 'Discord' has already been declared
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)  
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)       
    at internal/main/run_main_module.js:17:11

**HELP!**

**Comment by Tahwi** [comment]
This has been going on for like 2 weeks

**Comment by bdbch** [comment]
Hey @Tahwi sorry for the problems you're experiencing.
We discontinued working on this package a while ago (3 years).

I've heard https://github.com/discord-akairo/discord-akairo is a good alternative as it's still well maintained.

If you don't want to switch:

> This has been going on for like 2 weeks

Did it work just fine before?

**Comment by lostdesign** [comment]
@Tahwi Devcord replaced Codlr with https://github.com/redxtech/devmod - check it out if you are interested.

**Comment by bdbch** [comment]
I'll close the issue. If you need further assistance feel free to reopen.
